name: Sync LeetCode Solutions

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync to algorithm-datastructure repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          source-directory: 'leetcode' # 원본 리포지토리의 LeetCode 폴더 경로
          destination-github-username: YOUR_USERNAME
          destination-repository-name: 'algorithm-datastructure'
          target-branch: main
          target-directory: 'leetcode' # 대상 리포지토리의 경로
