name: Sync LeetCode Solutions

on:
  push:
	@@ -7,17 +7,27 @@ on:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync to algorithm-datastructure repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          source-directory: 'LeetCode' # 원본 리포지토리의 LeetCode 폴더 로컬 경로
          destination-github-username: 'Ooyd'
          destination-repository-name: 'algorithm-and-data-structure'
          target-branch: main
          target-directory: 'LeetCode' # 대상 디렉토리
