name: Sync Repositories

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout LeetCode Repository
      uses: actions/checkout@v2
      with:
        repository: 'Ooyd/LeetCode'
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Get Last Commit Message
      id: commit-message
      run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

    - name: Sync Files to algorithm-and-data-structure Repository
      run: |
        git config --global user.email "qk1413@naver.com"
        git config --global user.name "june0929"
        git clone https://github.com/Ooyd/algorithm-and-data-structure.git
        cp -R LeetCode/* algorithm-and-data-structure/LeetCode/
        cd algorithm-and-data-structure
        git add .
        git commit -m "${{ steps.commit-message.outputs.message }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
